require File.join('omniauth', 'strategies', 'google_analytics')
require File.join('omniauth', 'strategies', 'google_adwords')
require File.join('omniauth', 'strategies', 'double_click')
require File.join('omniauth', 'strategies', 'double_click_bid_manager')
require File.join('omniauth', 'strategies', 'google_search_console')